# Generated by Django 3.0.8 on 2020-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_choice', models.CharField(choices=[('0', 'IP Estático'), ('1', 'IP Dinâmico')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='config',
            name='op_mode',
            field=models.BooleanField(),
        ),
    ]
