# Generated by Django 3.0.8 on 2020-08-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0002_auto_20200728_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
