# Generated by Django 3.0.8 on 2020-08-10 17:44

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0003_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_choice', models.CharField(choices=[('0', 'IP Estático'), ('1', 'IP Dinâmico')], max_length=1)),
                ('op_mode_gateway', models.BooleanField(default=True)),
                ('op_mode_router', models.BooleanField(default=False)),
                ('mac_adress', macaddress.fields.MACAddressField(blank=True, integer=True, null=True)),
                ('ip_adress', models.GenericIPAddressField()),
                ('mask_adress', models.GenericIPAddressField()),
                ('gateway_adress', models.GenericIPAddressField()),
            ],
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
