# Generated by Django 3.0.8 on 2020-08-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0004_auto_20200810_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config_device',
            name='op_mode_gateway',
        ),
        migrations.RemoveField(
            model_name='config_device',
            name='op_mode_router',
        ),
        migrations.AddField(
            model_name='config_device',
            name='op_mode',
            field=models.CharField(choices=[('0', 'Gateway'), ('1', 'Roteador')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
