# Generated by Django 3.0.8 on 2020-08-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_site', '0005_auto_20200810_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_ver', models.CharField(max_length=20)),
                ('hardware_ver', models.CharField(max_length=20)),
            ],
        ),
    ]
